version: '3'
services:

  elasticsearch:
    container_name: elasticsearch
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.8.5"
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
     - "9200:9200"

 logstash:
    container_name: logstash
    image: "docker.elastic.co/logstash/logstash:6.8.5"
    ports:
     - "5000:5000"
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/share/logstash/pipeline:ro
    links:
     - "elasticsearch:elasticsearch"
    depends_on:
     - "elasticsearch"


  kibana:
    container_name: kibana
    image: "docker.elastic.co/kibana/kibana:6.8.5"
    ports:
     - "5601:5601"
    links: 
     - "elasticsearch:elasticsearch"
    depends_on:
     - "elasticsearch"

 